const PLANT_DATA = [
  {
    "num": 1,
    "name": "Hirao",
    "qty": 1,
    "stock": 1,
    "cost": 300.0,
    "price": 450,
    "type": "Mature",
    "maturity": "2022",
    "breeder": "Anton van Wouw Show",
    "notes": "Checked 4 Aug 2024. 1x 12 leaves"
  },
  {
    "num": 2,
    "name": "Compact Hirao Green",
    "qty": 5,
    "stock": 2,
    "cost": 150.0,
    "price": 400,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Sean Chubb",
    "notes": "Checked 4 Aug 2024. 1x 10 leaves, 1x 10 leaves"
  },
  {
    "num": 3,
    "name": "Pure Hirao cross",
    "qty": 1,
    "stock": 1,
    "cost": 500.0,
    "price": 600,
    "type": "Mature",
    "maturity": "2022",
    "breeder": "Utopia Clivias",
    "notes": "Checked 4 Aug 2024. 1x 8 leaves with 2 offsets"
  },
  {
    "num": 4,
    "name": "Group 1 Yellow",
    "qty": 1,
    "stock": 1,
    "cost": 0,
    "price": 500,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Carlene (original)",
    "notes": "Carlene's original. 4-51-86"
  },
  {
    "num": 5,
    "name": "Hirao with self cross",
    "qty": 1,
    "stock": 1,
    "cost": 350.0,
    "price": 750,
    "type": "Mature",
    "maturity": "2022",
    "breeder": "Utopia Clivias",
    "notes": "Checked 4 Aug 2024. 1x Mature"
  },
  {
    "num": 6,
    "name": "Blitz",
    "qty": 5,
    "stock": 1,
    "cost": 200.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2024",
    "breeder": "Sean Chubb",
    "notes": "Only 1 survived"
  },
  {
    "num": 7,
    "name": "Hash x Hirao Green",
    "qty": 5,
    "stock": 3,
    "cost": 150.0,
    "price": 750,
    "type": "Mature",
    "maturity": "2024",
    "breeder": "Sean Chubb",
    "notes": "4 survived. Checked 4 Aug 2024. 1x 11L, 1x 10L, 1x 15L"
  },
  {
    "num": 8,
    "name": "Unknown Hirao",
    "qty": 1,
    "stock": 1,
    "cost": 200.0,
    "price": 750,
    "type": "Mature",
    "maturity": "2022",
    "breeder": "Anton van Wouw Show",
    "notes": "Checked 4 Aug 2024. 1x Mature"
  },
  {
    "num": 10,
    "name": "Paul Kloeck Hiraos",
    "qty": 6,
    "stock": 7,
    "cost": 2520.0,
    "price": 3800,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Kential Grove (Craig)",
    "notes": "Checked 4 Aug 2024. 1x 8L, 1x 9L, 1x 9L, 1x 7L, 1x Mature, 1x offset 7L, 1x 19L. Plus one extra offset"
  },
  {
    "num": 11,
    "name": "Hirao Francois van Rooyen",
    "qty": 1,
    "stock": 6,
    "cost": 1500.0,
    "price": 2250,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Francois van Rooyen (Gem Wildflowers)",
    "notes": "Checked 4 Aug 2024. 1x 8L, 1x 10L, 1x 10L, 1x 2L, 1x 11L, 1x 10L pigmented. Double umbel 2021. Sold original for R1500 to Desmond Botes"
  },
  {
    "num": 13,
    "name": "Charl's Green x Hirao",
    "qty": 2,
    "stock": 1,
    "cost": 2500.0,
    "price": 3750,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Utopia Clivias",
    "notes": "Checked 4 Aug 2024. 1x mature. First flower 2020"
  },
  {
    "num": 14,
    "name": "Hirao x Charl's Green",
    "qty": 1,
    "stock": 1,
    "cost": 2500.0,
    "price": 3750,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Utopia Clivias",
    "notes": "Checked 4 Aug 2024. 1x mature. Great colour and flower count"
  },
  {
    "num": 15,
    "name": "Green Hirao x Charl's Green",
    "qty": 1,
    "stock": 1,
    "cost": 1000.0,
    "price": 1500,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Dawie Strydom",
    "notes": "Checked 4 Aug 2024. 1x Mature + offset 8 leaves"
  },
  {
    "num": 16,
    "name": "Hirao Dark Green offset Toshio Koike",
    "qty": 1,
    "stock": 1,
    "cost": 750.0,
    "price": 1100,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Dawie Strydom",
    "notes": "Checked 4 Aug 2024. 1x Mature"
  },
  {
    "num": 17,
    "name": "Hirao-ES x Hirao",
    "qty": 1,
    "stock": 1,
    "cost": 750.0,
    "price": 1100,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Dawie Strydom",
    "notes": "Checked 4 Aug 2024. Mature. Sold 2 offsets to August van Heerden R500 Oct 2022"
  },
  {
    "num": 18,
    "name": "Black Magic Red",
    "qty": 2,
    "stock": 2,
    "cost": 600.0,
    "price": 700,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Garden World Show",
    "notes": "Checked 4 Aug 2024. 1x 13 leaves, 1x Mature +20 leaves. Planted 2017"
  },
  {
    "num": 19,
    "name": "Bronze x Gunrao (Gunston x Hirao)",
    "qty": 1,
    "stock": 1,
    "cost": 125.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Utopia Clivias",
    "notes": "Code SD13. Planted 2018"
  },
  {
    "num": 20,
    "name": "Donalie x Crown Prince F1",
    "qty": 1,
    "stock": 1,
    "cost": 150.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Utopia Clivias",
    "notes": "Code SD3. Checked 4 Aug 2024. 1x 9 leaves"
  },
  {
    "num": 21,
    "name": "Group 3 Yellow with pink tips x Self",
    "qty": 1,
    "stock": 1,
    "cost": 150.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Utopia Clivias",
    "notes": "Code SD6. New mutation. Checked 4 Aug 2024. 1x 12 leaves"
  },
  {
    "num": 22,
    "name": "Vico Green x Sibling",
    "qty": 1,
    "stock": 1,
    "cost": 120.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Utopia Clivias",
    "notes": "Code SD7. Checked 4 Aug 2024. 1x 8 leaves"
  },
  {
    "num": 23,
    "name": "Belgium Bronze x (Florid White Lips Ghost x Belgium Bronze)",
    "qty": 1,
    "stock": 1,
    "cost": 120.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Utopia Clivias",
    "notes": "Code SD11. Checked 4 Aug 2024. 1x 14 leaves"
  },
  {
    "num": 24,
    "name": "Vico Pink Quartz x Lotter Pink",
    "qty": 1,
    "stock": 1,
    "cost": 175.0,
    "price": 250,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Utopia Clivias",
    "notes": "Code SD15"
  },
  {
    "num": 25,
    "name": "Tipperary Green Throat 1 x 2",
    "qty": 1,
    "stock": 1,
    "cost": 150.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2023",
    "breeder": "Utopia Clivias",
    "notes": "Code SD14. Checked 4 Aug 2024. 1x 9 leaves"
  },
  {
    "num": 26,
    "name": "Utopia Red F1 x Oxblood",
    "qty": 1,
    "stock": 1,
    "cost": 65.0,
    "price": 500,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Utopia Clivias",
    "notes": "Planted 9 Jul 2020. Checked 4 Aug 2024. 1x 15 leaves"
  },
  {
    "num": 27,
    "name": "Charl's Green x Stoetbul",
    "qty": 3,
    "stock": 3,
    "cost": 150.0,
    "price": 400,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Cliviamart",
    "notes": "Planted 11 Jun 2020. Group 2 yellows. Checked 4 Aug 2024. 1x 9L, 1x 8L, 1x 10L"
  },
  {
    "num": 28,
    "name": "Absynth x TK Green",
    "qty": 3,
    "stock": 2,
    "cost": 150.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Cliviamart",
    "notes": "Planted 11 Jun 2020. Breeding green GR2. Checked 4 Aug 2024. 1x 8L, 1x 4L"
  },
  {
    "num": 29,
    "name": "Classic Green (out of Hirao) x Japanese Group 2 green throat",
    "qty": 3,
    "stock": 3,
    "cost": 120.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Karkloof Clivias",
    "notes": "Planted Jun 2020. Checked 4 Aug 2024. 1x 7L, 1x 7L, 1x 8L"
  },
  {
    "num": 30,
    "name": "Shiges Hirao x Hirao",
    "qty": 3,
    "stock": 2,
    "cost": 150.0,
    "price": 400,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Karkloof Clivias",
    "notes": "Planted Jun 2020. 1 seedling died Jun 2022. Checked 4 Aug 2024. 1x 12L, 1x 5L"
  },
  {
    "num": 31,
    "name": "Light Yellow",
    "qty": 3,
    "stock": 3,
    "cost": 100.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Clivia Paradise",
    "notes": "Planted Jun 2020. Checked 4 Aug 2024. 1x 10L, 1x 8L, 1x 10L"
  },
  {
    "num": 32,
    "name": "777 Inzima x Self",
    "qty": 5,
    "stock": 3,
    "cost": 1000.0,
    "price": 1500,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Sean Chubb",
    "notes": "Planted 2 Aug 2020. Checked 4 Aug 2024. 1x 12L, 1x 12L, 1x 11L"
  },
  {
    "num": 33,
    "name": "Recurve Green x Hirao",
    "qty": 5,
    "stock": 3,
    "cost": 200.0,
    "price": 250,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Chris Viljoen",
    "notes": "Garden World show. Planted 30 Aug 2020. Checked 4 Aug 2024. 1x 4L, 1x 6L, 1x 8L"
  },
  {
    "num": 34,
    "name": "JW Red x Wildfire",
    "qty": 1,
    "stock": 1,
    "cost": 45.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Utopia Clivias",
    "notes": "Planted 9 Jul 2020. Checked 4 Aug 2024. 1x 10 leaves"
  },
  {
    "num": 35,
    "name": "Crimson x Wildfire",
    "qty": 1,
    "stock": 1,
    "cost": 55.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Utopia Clivias",
    "notes": "Planted 9 Jul 2020. Checked 4 Aug 2024. 1x 6 leaves"
  },
  {
    "num": 36,
    "name": "Best Red RL x Triplet Red",
    "qty": 1,
    "stock": 1,
    "cost": 65.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Utopia Clivias",
    "notes": "Planted 9 Jul 2020. Checked 4 Aug 2024. 1x 6 leaves"
  },
  {
    "num": 38,
    "name": "Catelyn EK x Davos (Group 1)",
    "qty": 1,
    "stock": 1,
    "cost": 75.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Utopia Clivias",
    "notes": "Planted 9 Jul 2020. Checked 4 Aug 2024. 1x 8 leaves"
  },
  {
    "num": 39,
    "name": "Variegated Yellow",
    "qty": 1,
    "stock": 1,
    "cost": 50.0,
    "price": 150,
    "type": "Mature",
    "maturity": "2024",
    "breeder": "Marius (Kempton Park)",
    "notes": ""
  },
  {
    "num": 40,
    "name": "Best Hirao 2016 x Hottie Hirao",
    "qty": 5,
    "stock": 4,
    "cost": 500.0,
    "price": 750,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Sean Chubb",
    "notes": "Planted 2 Aug 2020. Checked 4 Aug 2024. 1x 7L, 1x 9L, 1x 10L, 1x 11L"
  },
  {
    "num": 41,
    "name": "(Charl's Green x Hirao) x Stoetbul",
    "qty": 3,
    "stock": 3,
    "cost": 300.0,
    "price": 450,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Cliviamart",
    "notes": "Planted 11 Jun 2020. Checked 4 Aug 2024. 1x 10L, 1x 14L, 1x 7L"
  },
  {
    "num": 42,
    "name": "Green Infinity (TKO x Hirao) x One of a kind",
    "qty": 2,
    "stock": 1,
    "cost": 190.0,
    "price": 400,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Utopia Clivias",
    "notes": "R95 each. Planted 9 Jul 2020. Checked 4 Aug 2024. 1x 11 leaves"
  },
  {
    "num": 43,
    "name": "Thurlow Complimentary Bronze",
    "qty": 5,
    "stock": 3,
    "cost": 0,
    "price": 300,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Sean Chubb (Thurlow)",
    "notes": "Free seeds. Planted 2 Aug 2020. Checked 4 Aug 2024. 1x 8L, 1x 9L, 1x 11L"
  },
  {
    "num": 44,
    "name": "Hirao White Green x Hirao",
    "qty": 10,
    "stock": 4,
    "cost": 300.0,
    "price": 750,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Chris Viljoen",
    "notes": "Garden World Show. Planted 30 Aug 2020. Checked 4 Aug 2024. 1x 10L, 1x 7L, 1x 15L, 1x 11L"
  },
  {
    "num": 45,
    "name": "TK Green x Hirao (PS)",
    "qty": 3,
    "stock": 2,
    "cost": 0,
    "price": 100,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Cliviamart",
    "notes": "1 died. Planted 11 Jun 2020"
  },
  {
    "num": 46,
    "name": "Jodhi Hirao x Hirao",
    "qty": 10,
    "stock": 9,
    "cost": 300.0,
    "price": 450,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Chris Viljoen",
    "notes": "Garden World Show. Planted 30 Aug 2020. Checked 4 Aug 2024. 1x 9L, 1x 7L, 1x 5L, 1x 9L, 1x 7L, 1x 13L, 1x 10L, 1x 9L, 1x 9L"
  },
  {
    "num": 47,
    "name": "Hirao x Hirao",
    "qty": 5,
    "stock": 4,
    "cost": 150.0,
    "price": 400,
    "type": "Mature",
    "maturity": "2025",
    "breeder": "Chris Viljoen",
    "notes": "Garden World Show. 1 died. Planted 30 Aug 2020. Checked 4 Aug 2024. 1x 8L, 1x 6L, 1x 5L, 1x 11L"
  },
  {
    "num": 48,
    "name": "Big Boy Show Orange",
    "qty": 1,
    "stock": 3,
    "cost": 500.0,
    "price": 600,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Garden World Show",
    "notes": "Olive Brummer Orange. 4 plants total. Planted 135+80 seeds Jun 2021. Checked 4 Aug 2024. 3x Mature"
  },
  {
    "num": 49,
    "name": "Interspecific (Orange)",
    "qty": 1,
    "stock": 1,
    "cost": 300.0,
    "price": 750,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Sean Chubb",
    "notes": "Garden World show 30 Aug 2020"
  },
  {
    "num": 50,
    "name": "Interspecific (Red)",
    "qty": 1,
    "stock": 1,
    "cost": 300.0,
    "price": 750,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Sean Chubb",
    "notes": "Garden World show 30 Aug 2020"
  },
  {
    "num": 51,
    "name": "Group 1 Yellow",
    "qty": 1,
    "stock": 1,
    "cost": 0,
    "price": 500,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Carlene (original)",
    "notes": "Carlene's original. 4-51-86"
  },
  {
    "num": 52,
    "name": "Four Marys Exquisite x Woodlands Beauty",
    "qty": 1,
    "stock": 1,
    "cost": 0,
    "price": 100,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021"
  },
  {
    "num": 53,
    "name": "Meng Huang Blush x Meili",
    "qty": 1,
    "stock": 1,
    "cost": 145.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021. Checked 4 Aug 2024. 1x 10 leaves"
  },
  {
    "num": 54,
    "name": "Carries Green x Pedigree Hirao",
    "qty": 1,
    "stock": 1,
    "cost": 95.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021. Checked 4 Aug 2024. 1x 9 leaves"
  },
  {
    "num": 55,
    "name": "Ice Ice Baby x Charl's Green",
    "qty": 1,
    "stock": 1,
    "cost": 125.0,
    "price": 200,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021"
  },
  {
    "num": 56,
    "name": "Raion x Tora",
    "qty": 1,
    "stock": 1,
    "cost": 95.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021. Checked 4 Aug 2024. 1x 8 leaves"
  },
  {
    "num": 57,
    "name": "Tora x Pedigree Hirao",
    "qty": 1,
    "stock": 1,
    "cost": 85.0,
    "price": 400,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021. Checked 4 Aug 2024. 1x 10 leaves"
  },
  {
    "num": 58,
    "name": "Guava x Tigers Eye",
    "qty": 1,
    "stock": 1,
    "cost": 75.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021. Checked 4 Aug 2024. 1x 10 leaves"
  },
  {
    "num": 59,
    "name": "Secret Strawberry Parfait x GGR",
    "qty": 1,
    "stock": 1,
    "cost": 85.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021. Checked 4 Aug 2024. 1x 8 leaves. Flowered in 2024!"
  },
  {
    "num": 60,
    "name": "Pixie Slippers x Happy Wanderer",
    "qty": 1,
    "stock": 1,
    "cost": 75.0,
    "price": 100,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021"
  },
  {
    "num": 61,
    "name": "Victorian Renaissance x Self",
    "qty": 1,
    "stock": 1,
    "cost": 65.0,
    "price": 100,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021"
  },
  {
    "num": 62,
    "name": "Tigers Eye x Stanmore Bronzed Green Girl",
    "qty": 1,
    "stock": 1,
    "cost": 200.0,
    "price": 400,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021. Checked 4 Aug 2024. 1x 13 leaves"
  },
  {
    "num": 63,
    "name": "Misty Mountain x Jade Amber",
    "qty": 1,
    "stock": 1,
    "cost": 95.0,
    "price": 150,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021"
  },
  {
    "num": 64,
    "name": "Efyd Original x Autumn Whisper",
    "qty": 1,
    "stock": 1,
    "cost": 0,
    "price": 100,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021"
  },
  {
    "num": 65,
    "name": "7Gun A x Star Power",
    "qty": 1,
    "stock": 1,
    "cost": 145.0,
    "price": 200,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Utopia Clivias",
    "notes": "Bought 25 Feb 2021"
  },
  {
    "num": 66,
    "name": "Mustard (Light Green Apricot Mr. Koiki x Yellow Bell) x Star Burst (Mincaul x Yellow Green Yellow Drops)",
    "qty": 3,
    "stock": 1,
    "cost": 300.0,
    "price": 450,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "Planted 6 Jun 2021"
  },
  {
    "num": 67,
    "name": "777-10 x Recurving Full Green Brown 777-1",
    "qty": 3,
    "stock": 1,
    "cost": 360.0,
    "price": 550,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "Planted 6 Jun 2021. Checked 4 Aug 2024. 1x 13 leaves"
  },
  {
    "num": 68,
    "name": "777-6 x Recurving Full Green Brown 777-1",
    "qty": 3,
    "stock": 3,
    "cost": 360.0,
    "price": 550,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "Planted 6 Jun 2021. Checked 4 Aug 2024. 1x 9L, 1x 11L, 1x 12L"
  },
  {
    "num": 69,
    "name": "Green Surprise 777-14 x Recurving Full Green Brown 777-1",
    "qty": 3,
    "stock": 3,
    "cost": 360.0,
    "price": 450,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "Planted 6 Jun 2021. Checked 4 Aug 2024. 1x 9L, 1x 9L, 1x 9L"
  },
  {
    "num": 70,
    "name": "Red Blush 777-16 x Recurving Full Green Brown 777-1",
    "qty": 3,
    "stock": 3,
    "cost": 360.0,
    "price": 550,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "Planted 6 Jun 2021. Checked 4 Aug 2024. 1x 6L, 1x 11L, 1x 8L"
  },
  {
    "num": 71,
    "name": "(Charl's Green x Hirao) x Charl's Green",
    "qty": 6,
    "stock": 2,
    "cost": 400.0,
    "price": 600,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Liz Boyd",
    "notes": "Planted 10 Jun 2021. Checked 4 Aug 2024. 1x 4L, 1x 4L"
  },
  {
    "num": 72,
    "name": "Party Time x Kiko",
    "qty": 3,
    "stock": 3,
    "cost": 250.0,
    "price": 400,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Liz Boyd",
    "notes": "Planted 10 Jun 2021"
  },
  {
    "num": 73,
    "name": "Golden Ren x Multi Interspec",
    "qty": 3,
    "stock": 3,
    "cost": 350.0,
    "price": 500,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Liz Boyd",
    "notes": "Planted 10 Jun 2021"
  },
  {
    "num": 74,
    "name": "Green Ivory x Hattori Yellow Blush",
    "qty": 3,
    "stock": 2,
    "cost": 150.0,
    "price": 200,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Liz Boyd",
    "notes": "Planted 10 Jun 2021. 1 seedling died Jun 2022"
  },
  {
    "num": 75,
    "name": "Dotti I x Multi Interspec",
    "qty": 3,
    "stock": 3,
    "cost": 350.0,
    "price": 500,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Liz Boyd",
    "notes": "Planted 10 Jun 2021"
  },
  {
    "num": 76,
    "name": "Nobilis x Robusta F1",
    "qty": 3,
    "stock": 3,
    "cost": 150.0,
    "price": 200,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Liz Boyd",
    "notes": "Planted 10 Jun 2021"
  },
  {
    "num": 77,
    "name": "Classic Peach x Mirajohn",
    "qty": 2,
    "stock": 2,
    "cost": 162.5,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Hilton Clivias",
    "notes": "Planted 17 May 2021. Checked 4 Aug 2024. 1x 8L, 1x 10L"
  },
  {
    "num": 78,
    "name": "(Alida x Nathaniel) x (Sussa x Alida)",
    "qty": 2,
    "stock": 2,
    "cost": 162.5,
    "price": 250,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Hilton Clivias",
    "notes": "Planted 17 May 2021"
  },
  {
    "num": 79,
    "name": "(Cameron Peach x Tamlyn) Light of Dawn Supreme",
    "qty": 2,
    "stock": 2,
    "cost": 325.0,
    "price": 400,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Hilton Clivias",
    "notes": "Planted 17 May 2021. Checked 4 Aug 2024. 1x 10L, 1x 9L"
  },
  {
    "num": 80,
    "name": "(Angelica Sibling x Angelica) x Angelica",
    "qty": 2,
    "stock": 2,
    "cost": 162.5,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Hilton Clivias",
    "notes": "Planted 17 May 2021. Checked 4 Aug 2024. 1x 10L, 1x 11L"
  },
  {
    "num": 81,
    "name": "(Ghost Piccottee x Avis Yellow) x (Her Majesty x Apoline)",
    "qty": 2,
    "stock": 2,
    "cost": 0,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Hilton Clivias",
    "notes": "Free. Planted 17 May 2021. Checked 4 Aug 2024. 1x 12L, 1x 14L"
  },
  {
    "num": 82,
    "name": "F1 Golden Dragon (Gol Drag x Yel Naka x Little Swan Blush) x Compact Tiger",
    "qty": 4,
    "stock": 2,
    "cost": 200.0,
    "price": 250,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "Half price. Planted 6 Jun 2021. Checked 4 Aug 2024. 1x 7L, 1x 9L"
  },
  {
    "num": 83,
    "name": "Compact Yellow Daruma (TK Dark Yellow x Best Yellow Daruma) x Compact Tiger",
    "qty": 3,
    "stock": 3,
    "cost": 150.0,
    "price": 200,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "Half price. Planted 6 Jun 2021"
  },
  {
    "num": 84,
    "name": "Variegated leaf (Compact Daruma from Japan 2010) x Compact Tiger",
    "qty": 3,
    "stock": 3,
    "cost": 150.0,
    "price": 200,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "Half price. Planted 6 Jun 2021"
  },
  {
    "num": 85,
    "name": "Charl's Green x Self or Greenwood",
    "qty": 10,
    "stock": 7,
    "cost": 0,
    "price": 400,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "Dawie Strydom",
    "notes": "No charge. Planted 6 Jun 2021. Checked 4 Aug 2024. 1x 7L, 1x 11L, 1x 9L, 1x 10L, 1x 8L, 1x 8L, 1x 8L"
  },
  {
    "num": 86,
    "name": "Ambar Downs Peach (Poorman's Peach)",
    "qty": 1,
    "stock": 5,
    "cost": 80.0,
    "price": 500,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Carlene (original)",
    "notes": "Carlene's original Peach Clivia. Favourite! Planted 72 seeds Jun 2021. Offset flowered Sep 2021. Checked 4 Aug 2024. 5 plants"
  },
  {
    "num": 87,
    "name": "(Athena x Hirao) x Tjokkie",
    "qty": 3,
    "stock": 3,
    "cost": 120.0,
    "price": 200,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Cliviamart",
    "notes": "Planted 20 Jun 2021"
  },
  {
    "num": 88,
    "name": "Efydd x Tjokkie",
    "qty": 3,
    "stock": 3,
    "cost": 150.0,
    "price": 200,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "Cliviamart",
    "notes": "Planted 20 Jun 2021"
  },
  {
    "num": 89,
    "name": "Royal Valor x (Royal Blush x Hattori)",
    "qty": 2,
    "stock": 2,
    "cost": 180.0,
    "price": 250,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021"
  },
  {
    "num": 90,
    "name": "(Naude Peach x Hattori) x (Naude Peach x Hattori)",
    "qty": 3,
    "stock": 1,
    "cost": 150.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021. Checked 4 Aug 2024. 1x 11 leaves"
  },
  {
    "num": 91,
    "name": "777 Bleeding Heart x (Naude Peach x Hattori)",
    "qty": 2,
    "stock": 1,
    "cost": 100.0,
    "price": 200,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021. Checked 4 Aug 2024. 1x 8 leaves"
  },
  {
    "num": 92,
    "name": "Emmadale x Love Child",
    "qty": 2,
    "stock": 2,
    "cost": 280.0,
    "price": 400,
    "type": "Seedling",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021"
  },
  {
    "num": 93,
    "name": "Brenthurst I/S x Emmadale",
    "qty": 1,
    "stock": 1,
    "cost": 100.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021. Checked 4 Aug 2024. 1x 12 leaves"
  },
  {
    "num": 94,
    "name": "(BxB) x McNeil GreenGirl x Autumn Whisper x Autumn Whisper",
    "qty": 3,
    "stock": 1,
    "cost": 100.0,
    "price": 750,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021. First flower August 2024. Checked 4 Aug 2024. 1x 16 leaves"
  },
  {
    "num": 95,
    "name": "Champagne Bubbles x (Tipperary Peach x Pretty Pink)",
    "qty": 3,
    "stock": 3,
    "cost": 100.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021. Checked 4 Aug 2024. 1x 12L, 1x 10L, 1x 10L"
  },
  {
    "num": 96,
    "name": "(Tipperary Peach x Pretty Pink) x Self",
    "qty": 3,
    "stock": 2,
    "cost": 100.0,
    "price": 300,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021. 1 seedling died Oct 2022. Checked 4 Aug 2024. 1x 10L, 1x 8L"
  },
  {
    "num": 97,
    "name": "Ngome",
    "qty": 1,
    "stock": 1,
    "cost": 700.0,
    "price": 1050,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "10 leaf offset. 23 Jul 2021"
  },
  {
    "num": 98,
    "name": "Emmadale x (Gunston x Star Green)",
    "qty": 2,
    "stock": 2,
    "cost": 180.0,
    "price": 750,
    "type": "Mature",
    "maturity": "2026",
    "breeder": "George Mann (Incredible Plants)",
    "notes": "Planted 23 Jul 2021. Checked 4 Aug 2024. 1x 8L, 1x 16L"
  },
  {
    "num": 99,
    "name": "Black Heart",
    "qty": 1,
    "stock": 1,
    "cost": 2000.0,
    "price": 3000,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Elroy (Clivias4sale WhatsApp)",
    "notes": "6 leaf seedling. 24 Jul 2021. Bred by Kobus Visser using Coromandel Bronze. Checked 4 Aug 2024. 1x Mature"
  },
  {
    "num": 100,
    "name": "Charl's Green x Hirao-White Stripe",
    "qty": 1,
    "stock": 4,
    "cost": 750.0,
    "price": 1100,
    "type": "Mature",
    "maturity": "Mature",
    "breeder": "Dawie Strydom",
    "notes": "Carlene bought for Anton's 40th birthday 12 Apr 2021. Checked 4 Aug 2024. 1x Mature, 3x offsets"
  }
];
